// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjaKGGXkSubzfca8bVRA0xdtVrN51YLr0',
    appId: '1:351271808328:web:5f35ac1d79ee279d72d77d',
    messagingSenderId: '351271808328',
    projectId: 'chat-36c90',
    authDomain: 'chat-36c90.firebaseapp.com',
    storageBucket: 'chat-36c90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC8g5F5SwV1V4ts7eOWxeuQclFNL_rmoM',
    appId: '1:351271808328:android:ff4cf196db0eea0c72d77d',
    messagingSenderId: '351271808328',
    projectId: 'chat-36c90',
    storageBucket: 'chat-36c90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGEYsicTC8GxMdeMA5_sfTXBNnOw5lk-8',
    appId: '1:351271808328:ios:58e6d5297ac225e772d77d',
    messagingSenderId: '351271808328',
    projectId: 'chat-36c90',
    storageBucket: 'chat-36c90.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGEYsicTC8GxMdeMA5_sfTXBNnOw5lk-8',
    appId: '1:351271808328:ios:58e6d5297ac225e772d77d',
    messagingSenderId: '351271808328',
    projectId: 'chat-36c90',
    storageBucket: 'chat-36c90.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
